#===WAPS to creat a string in 3 different ways:
s_1="Python programing"    # using double quotes...
s_2='Java programing'      # using single quotes...
s_3="""C programing"""     #using triple quotes....
print(s_1,s_2,s_3,sep='\n')
print()